unicom:
  url: http://www.unicom.com
logging:
  level:
    root: info
    com.piggsoft: debug
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.206.178.236:3306/auto?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root